<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Contoso.NotificationRelay.Domain</RootNamespace>
    <AssemblyName>NotificationRelay.Domain</AssemblyName>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

</Project>
