<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Contoso.NotificationRelay.Application</RootNamespace>
    <AssemblyName>NotificationRelay.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotificationRelay.Domain\NotificationRelay.Domain.csproj" />
  </ItemGroup>

</Project>
